"""empty message

Revision ID: ed3f42ace020
Revises: 
Create Date: 2019-10-24 01:21:52.173446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3f42ace020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_dir_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_dir_id'], ['dir.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['dir.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('dir')
    # ### end Alembic commands ###
